#!/bin/bash
TIME=$(sed -n 's/^ Time in seconds *= *\([0-9\.]*\)$/\1/p' output/run.out)
TASKS=$(sed -n 's/^ Total threads *= *\([0-9\.]*\)$/\1/p' output/run.out)
cat > output/summary.json <<EOF
{
  "name":"hackbench",
  "ipanema":"${PATH_TO_IPANEMA_MODULE}",
  "time":${TIME},
  "tasks":${TASKS}
}
EOF
./report.py output.hdf5 output
