#!/bin/bash
set -e -x
img=scheddisplay
docker build -t ${img} .
docker run --rm \
       -e BOKEH_ALLOW_WS_ORIGIN=localhost:5006 \
       -v ${PWD}/examples:/home/server/examples:ro \
       -v ${PWD}/examples/notebook:/home/server/examples/notebook \
       -p 5006:5006 \
       -p 443:443 \
       ${img}
