#!/bin/bash
set -e -u

main() {
    prog="$1"
    shift
    
    case "${IPANEMA_MODULE}" in
    	"")
	    exec "${prog}" "${@}"
	    ;;
	*)
	    # Check if kernel support ipanema API
	    [[ -f /proc/ipanema/policies ]]

	    # Check if module.ko exists
	    [[ -f "/lib/modules/${KERNEL}/kernel/kernel/sched/ipanema/${IPANEMA_MODULE}.ko" ]]

	    # Check if module description match pattern
	    # IPANEMA_POLICY_NAME=$(modinfo -F name "${PATH_TO_IPANEMA_MODULE}")
	    # IPANEMA_POLICY_DESCRIPTION=$(modinfo -F description "${PATH_TO_IPANEMA_MODULE}")
	    # [[ ${IPANEMA_POLICY_DESCRIPTION} = "${IPANEMA_POLICY_NAME} scheduling policy" ]]

	    # Check if module is compiled for current kernel
	    # IPANEMA_POLICY_KERNEL=$(modinfo -F vermagic "${PATH_TO_IPANEMA_MODULE}" | awk '{print $1}')
	    # [[ $(uname -r) = ${IPANEMA_POLICY_KERNEL} ]]

	    # Unload module first if already loaded.
	    module_is_loaded_and_could_not_be_unloaded () {
		(lsmod | awk '{print $1}' | grep -q "^${IPANEMA_MODULE}\$") && ! rmmod "${IPANEMA_MODULE}"
	    }
	    while module_is_loaded_and_could_not_be_unloaded
	    do
		echo 'module is loaded and could not be unloaded'
		sleep 10
	    done
	    # insmod "${PATH_TO_IPANEMA_MODULE}"
	    modprobe "${IPANEMA_MODULE}"

	    # Get ID
	    grep -q "${IPANEMA_MODULE}" /proc/ipanema/policies
	    IPANEMA_POLICY_ID=$(grep "${IPANEMA_MODULE}" /proc/ipanema/policies | awk '{print $1}')
	    exec ipastart "${IPANEMA_POLICY_ID}" "${prog}" "${@}"
	    ;;
    esac
}
main "$@"
