#!/bin/bash
set -u -e -x
rm -rf "${OUTPUT}"
source ${BENCH}/cleanup
source prepare
source ${BENCH}/prepare
source ${MONITORING}/start
(source ./time ${BENCH}/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err) &
wait $!
source ${MONITORING}/stop
source report
source ${BENCH}/report
source ${MONITORING}/report
tar cf "${OUTPUT}.tar" "${OUTPUT}"
source ${BENCH}/cleanup
source cleanup
