#!/bin/bash
dmesg > ${OUTPUT}/dmesg.report
cat > ${OUTPUT}/report.main.json <<EOF
{
  "kernel" : {
  "version" : "$(uname -r)",
  "cmdline" : "$(cat /proc/cmdline)"
  },
  "cpu" : {
  "scaling_governor" : "$(sort /sys/devices/system/cpu/cpufreq/policy*/scaling_governor | uniq)",
  "no_turbo" : "$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)"
  },
  "bench" : {
    "prepare" : $(./2jsonString ${BENCH}/prepare),
    "cleanup" : $(./2jsonString ${BENCH}/cleanup),
    "report"  : $(./2jsonString ${BENCH}/report),
    "run"     : $(./2jsonString ${BENCH}/run)
  },
  "monitoring" : {
    "start"  : $(./2jsonString ${MONITORING}/start),
    "stop"   : $(./2jsonString ${MONITORING}/stop),
    "report" : $(./2jsonString ${MONITORING}/report)
  },
  "main" : $(./2jsonString <(set))
}
EOF
