#!/bin/bash
set -e -u
prog="${1}"
shift

# Cleanup
if [[ -d ./rootproc ]]
then
	if mount | grep -q $(realpath ./rootproc )
	then
		umount ./rootproc
	fi
	rmdir ./rootproc
fi

# Prepare
mkdir ./rootproc
mount --bind /proc ./rootproc

exec unshare -mpf --mount-proc -- "${prog}" "${@}"
