#!/bin/bash
[[ $((TASKS%40)) -eq 0 ]] ||
   { echo 'TASKS%40'; exit 1; }
export GROUP=$((TASKS/40))
mkdir output
gcc -shared -fPIC record_gettimeofday.c -o record_gettimeofday.so -ldl
export LD_PRELOAD=./record_gettimeofday.so
