#!/bin/bash
set -u -e -x
! [ -f ${HDF5} ]
source cleanup
source prepare
[ -n "${MONITOR}" ] && source monitoring_start
/usr/bin/time \
    -f "%e" \
    ./run > >(tee output/run.out) 2> >(tee output/run.err) &
wait
[ -n "${MONITOR}" ] && source monitoring_stop
source report
source cleanup
