#!/bin/bash
set -u -e -x
source cleanup
source prepare
source monitoring_start
/usr/bin/time \
    -f "%e" \
    ./run > >(tee output/run.out) 2> >(tee output/run.err) &
wait
source monitoring_stop
source report
source cleanup
