#!/bin/bash

: ${TASKS}
. $(dirname "$0")/inc

if ! [ -f ${tar} ]
then
    wget --quiet https://www.nas.nasa.gov/assets/npb/NPB3.4.tar.gz -O ${tar}
fi

if ! [ -f ${bench_dir} ]
then
    tar -C ${base_dir} -xvzf ${tar}
fi

if ! [ -f ${bench_dir}/config/make.def ]
then
    cp ${bench_dir}/config/make.def.template ${bench_dir}/config/make.def
fi

if ! [ -f ${exe} ]
    cd $bench_dir
    make cg CLASS=C
fi

dmesg -C

