#!/bin/bash
. inc

: ${TASKS}

if ! [ -f ${tar} ]
then
    wget --quiet https://www.nas.nasa.gov/assets/npb/NPB3.4.tar.gz -O ${tar}
fi

if ! [ -f ${exe} ]
then
    tar -C ${base_dir} -xvzf ${tar}
    cp $bench_dir/config/make.def.template $bench_dir/config/make.def
    cd $bench_dir
    make cg CLASS=C
fi

dmesg -C

