#!/bin/bash
set -u -e -x
source ${BENCH}/cleanup
source ${BENCH}/prepare
source ${MONITORING}/start
source ./time > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
source ${MONITORING}/stop
source report
source ${BENCH}/report
source ${MONITORING}/report
tar czf "${OUTPUT}.tgz" "${OUTPUT}"
source ${BENCH}/cleanup
