#!/bin/bash
set -u -e -x
rm -rf "${OUTPUT}"
source ${BENCH}/cleanup
mkdir -p "${OUTPUT}"
source ${BENCH}/prepare
source ${MONITORING}/start
source ./time ${BENCH}/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
source ${MONITORING}/stop
source report
source ${BENCH}/report
source ${MONITORING}/report
tar czf "${OUTPUT}.tgz" "${OUTPUT}"
source ${BENCH}/cleanup
rm -rf "${OUTPUT}"
